# permissions to do viewer releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-viewer-role
rules:
- apiGroups:
  - alauda.io.alauda.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alauda.io.alauda.io
  resources:
  - releases/status
  verbs:
  - get
