image:
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
global:
  images:
    captain:
      repository: alaudapublic/captain
      tag: v1.5.0
