/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "alauda.io/captain/pkg/apis/app/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHelmRequests implements HelmRequestInterface
type FakeHelmRequests struct {
	Fake *FakeAppV1alpha1
	ns   string
}

var helmrequestsResource = schema.GroupVersionResource{Group: "app.alauda.io", Version: "v1alpha1", Resource: "helmrequests"}

var helmrequestsKind = schema.GroupVersionKind{Group: "app.alauda.io", Version: "v1alpha1", Kind: "HelmRequest"}

// Get takes name of the helmRequest, and returns the corresponding helmRequest object, and an error if there is any.
func (c *FakeHelmRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.HelmRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(helmrequestsResource, c.ns, name), &v1alpha1.HelmRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmRequest), err
}

// List takes label and field selectors, and returns the list of HelmRequests that match those selectors.
func (c *FakeHelmRequests) List(opts v1.ListOptions) (result *v1alpha1.HelmRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(helmrequestsResource, helmrequestsKind, c.ns, opts), &v1alpha1.HelmRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HelmRequestList{ListMeta: obj.(*v1alpha1.HelmRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.HelmRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helmRequests.
func (c *FakeHelmRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(helmrequestsResource, c.ns, opts))

}

// Create takes the representation of a helmRequest and creates it.  Returns the server's representation of the helmRequest, and an error, if there is any.
func (c *FakeHelmRequests) Create(helmRequest *v1alpha1.HelmRequest) (result *v1alpha1.HelmRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(helmrequestsResource, c.ns, helmRequest), &v1alpha1.HelmRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmRequest), err
}

// Update takes the representation of a helmRequest and updates it. Returns the server's representation of the helmRequest, and an error, if there is any.
func (c *FakeHelmRequests) Update(helmRequest *v1alpha1.HelmRequest) (result *v1alpha1.HelmRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(helmrequestsResource, c.ns, helmRequest), &v1alpha1.HelmRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHelmRequests) UpdateStatus(helmRequest *v1alpha1.HelmRequest) (*v1alpha1.HelmRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(helmrequestsResource, "status", c.ns, helmRequest), &v1alpha1.HelmRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmRequest), err
}

// Delete takes name of the helmRequest and deletes it. Returns an error if one occurs.
func (c *FakeHelmRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(helmrequestsResource, c.ns, name), &v1alpha1.HelmRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelmRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(helmrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HelmRequestList{})
	return err
}

// Patch applies the patch and returns the patched helmRequest.
func (c *FakeHelmRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HelmRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(helmrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HelmRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmRequest), err
}
