# check milestone
has_milestone = gitlab.mr_json["milestone"] != nil
warn("This MR does not refer to an existing milestone", sticky: true) unless has_milestone

# check label
failure "Please add labels to this MR" if gitlab.mr_labels.empty?


# check jira
jira.check(
  key: ["DEV", "INCI", "ACP"],
  url: "http://jira.alaudatech.com/browse",
  search_title: true,
  search_commits: true,
  fail_on_warning: false,
  report_missing: true,
  skippable: true
)


# Ensure a clean commits history
if git.commits.any? { |c| c.message =~ /^Merge branch/ }
  warn('Please rebase to get rid of the merge commits in this PR')
end


# Warn when there is a big PR
warn("Big PR, try to keep changes smaller if you can") if git.lines_of_code > 500


# commit message
commit_lint.check
