/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ChartRepoListerExpansion allows custom methods to be added to
// ChartRepoLister.
type ChartRepoListerExpansion interface{}

// ChartRepoNamespaceListerExpansion allows custom methods to be added to
// ChartRepoNamespaceLister.
type ChartRepoNamespaceListerExpansion interface{}

// HelmRequestListerExpansion allows custom methods to be added to
// HelmRequestLister.
type HelmRequestListerExpansion interface{}

// HelmRequestNamespaceListerExpansion allows custom methods to be added to
// HelmRequestNamespaceLister.
type HelmRequestNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}
