apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: captain
  name: captain
  namespace: captain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captain
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: captain
    spec:
      containers:
        - command:
            - /captain/captain
            - -cluster-namespace=captain
            - -chartrepo-namespace=captain
          image: alaudapublic/captain
          imagePullPolicy: IfNotPresent
          name: captain
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 512m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: certs
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            optional: true
            secretName: captain-webhook-cert

