apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: captain
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: captain
subjects:
    - kind: ServiceAccount
      name: default
      namespace: {{ .Release.Namespace }}
