kind: Deployment
apiVersion: extensions/v1beta1
spec:
  selector:
    matchLabels:
      app: captain
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.global.images.captain.repository }}:{{ .Values.global.images.captain.tag }}"
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.policy }}
          command:
            - /manager
          args:
            - "--cluster-namespace={{ .Release.Namespace }}"
            - "--chartrepo-namespace={{ .Release.Namespace }}"
            - "--metrics-addr=127.0.0.1:6060"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: certs
            mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
      - name: certs
        secret:
          optional: true
          secretName: captain-webhook-cert
    metadata:
      labels:
        app: captain
metadata:
  name: captain
  namespace: {{ .Release.Namespace }}
