apiVersion: v1
kind: Service
metadata:
  name: captain
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 9443
      name: webhook
    - port: 6060
      targetPort: 6060
      name: metrics
  selector:
    app: captain
