apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chartrepos.app.alauda.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: app.alauda.io
  version: v1alpha1
  names:
    kind: ChartRepo
    listKind: ChartRepoList
    plural: chartrepos
    singular: chartrepo
    shortNames:
      - ctr
  additionalPrinterColumns:
    - name: URL
      type: string
      description: The url of this chart repo
      JSONPath: .spec.url
    - name: Phase
      type: string
      description: The phase of this ChartRepo
      JSONPath: .status.phase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - url