apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: charts.app.alauda.io
spec:
    group: app.alauda.io
    version: v1alpha1
    names:
        kind: Chart
        listKind: ChartList
        plural: charts
        singular: chart
    additionalPrinterColumns:
        - name: Version
          type: string
          JSONPath: .spec.versions[0].version
        - name: AppVersion
          type: string
          JSONPath: .spec.versions[0].appVersion
        - name: Age
          type: date
          JSONPath: .metadata.creationTimestamp
    scope: Namespaced