name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Restore Cache
      uses: actions/cache@preview
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

    - name: Get dependencies
      run: make mod

    - name: Lint
      run: make fmt && make vet

    - name: Build
      run: make manager
